[package]
name = "minecraft_client"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
macros = { path = "./macros" }
bitflags = "2.9.1"
parking_lot = { version = "0.12.4", features = ["arc_lock"] }
log = "0.4.27"
env_logger = "0.11.8"

[workspace]
members = ["macros"]
